### ISSUE TITLE
🚀 Feature Request: Add dependabot.yml for GitHub Actions & Dev Container Updates 🚀

### ISSUE THREAD

**Issue by 0GiS0** [0GiS0/github-copilot-loves-accesibility#20]
Hi team! 👋

I’d like to request the addition of a **dependabot.yml** configuration to this repository.  
This will help us automatically keep our **GitHub Actions workflows** and **dev container dependencies** up to date! 🔄✨

**Why?**
- 🛡️ Improved security with timely dependency updates
- 📦 Reduced technical debt and manual maintenance
- ⚡ Smoother CI/CD and developer onboarding experience

**What to update?**
- GitHub Actions (`.github/workflows/`)
- Dev container (`.devcontainer/`)

**Possible dependabot.yml example:**
```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
```

Thanks for considering this enhancement! 🙏  
Let me know if I can help set it up. 😊
